= Poiji2

This is an advanced fork of https://github.com/ozlerhakan/poiji. +
Many thanks to ozlerhakan for inspiration.

Apache POI library required as dependency to work with xlsx and xls. Tested with dependency 'org.apache.poi:poi-ooxml:4.1.2'.

In your Maven/Gradle project, first add the corresponding dependency:

.maven
[source,xml]
----
<dependency>
    <groupId>io.github.vaa25</groupId>
    <artifactId>poiji2</artifactId>
    <version>1.2.0</version>
</dependency>

----

.gradle
[source,groovy]
----
dependencies {
    implementation 'io.github.vaa25:poiji2:1.2.0'
}
----

You can find feature descriptions in https://github.com/ozlerhakan/poiji README

Supported features: 1 - 17.

Also:

- Poiji2 is thread-safe.
- Poiji2 reads 30% faster than Poiji (see ConcurrentTest: synchronized read for Poiji vs synchronized optimized read for Poiji2).
- Poiji2 can write (use Poiji.toExcel(...)).
- Poiji2 can work with CSV (use PoijiExcelType.CSV, can be used without poi-ooxml dependency).
- Poiji2 can transpose sheet (use PoijiOptions.transposed). WARNING! Whole document loaded in memory.
- Poiji2 has mandatory column validation (use @ExcelCellName.mandatory).
- Poiji2 can collect parse exceptions in Entity object (use @ExcelParseExceptions on Map<String, ExcelParseException>).
- Poiji2 can transform excel to Stream (use Poiji.fromExcelToStream(...)). WARNING! XLSX takes double time more than transform to List.
- Poiji2 has usable builders for any case (ex. use Poiji.<JavaClass>fromExcel().withSource(new File(...)).withJavaType(JavaClass.class).toStream())

